name: "Close inactive issues"
on:
  schedule:
    # Run every day at 1:30 UTC
    - cron: '30 1 * * *'
  workflow_dispatch: # Allow manual run

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 150
          days-before-issue-close: 30
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within 30 days."
          close-issue-message: "This issue has been automatically closed due to sustained inactivity."
          stale-issue-label: "stale"
          # Optional: specify exempt labels, such as "bug" or "feature"
          # exempt-issue-labels: "bug,feature"
